// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnyxwsoskzvjykckafsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdueXh3c29za3p2anlrY2thZnNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MjU1MjQsImV4cCI6MjA2MjEwMTUyNH0.yripqfzPnE43WuLNIBW0EYhpJARpuO0b7MR4a8fb7B0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);